### ISSUE TITLE
[chore]: Post schema design, fix course view workflows

### ISSUE THREAD

**Issue by amezng** [torqbit/torqbit#568]
- [x] #574
- [x] Able to view the detail of enrolled course
- [x] #576
- [x] Able to start the course. `Failed`, due to incorrect lesson id in the `start` link.
- [x] Able to resume the course
- [x] Able to view the video
- [x] Able to post queries and replies
- [x] Able to receive the notification
- [x] Able to click the notification and land on the queries page. Incorrect course Id displayed.
- [x] Able to mark the lesson as completed
- [x] Able to receive the certificate on completion
- [x] #578

**Comment by mehrab-alam** [comment]
> * [ ]  Able to list the enrolled courses
> * [ ]  Able to get the course detail after enrollment 
> * [ ]  Able to view the detail of enrolled course
> * [ ]  Able to view the video
> * [ ]  Able to post queries and replies
> * [ ]  Able to mark the lesson as completed
> * [ ]  Able to receive the certificate on completion
